pre-commit:
  parallel: false
  commands:
    biome:
      run: pnpm exec biome check --no-errors-on-unmatched .
    typecheck:
      run: pnpm run typecheck

commit-msg:
  commands:
    commitlint:
      run: pnpm exec commitlint --edit {1}
